# TODO Fix PHPUnit testing of only custom themes/modules
# TODO Look into Portainer
# TODO Look into traefik - I don't think this is necessary, as Lando handles what this would do

env_file:
  - lando/lando.env

recipe: drupal8

config:
  php: 7.3
  via: apache
  webroot: web
  xdebug: false
  drush: false
  conf:
    php: lando/config/php.ini
    mysql: lando/config/my.cnf

services:
  database:
    type: mysql:5.7
#    portforward: 3310
  pma:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    composer:
      phpunit/phpunit: 8
      behat/behat: 3.3.1
    run:
      - "ln -s /usr/local/bin/composer /usr/local/bin/composer.phar"
    run_as_root:
      - "bash /app/lando/scripts/build.sh"
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://learn-drupal8.lndo.site"  # TODO Get this out of this file, but it doesn't seem to work in .lando.base.yml
  node:
    type: node:10
    globals:
      gulp-cli: latest
    build:
      - "cd $LANDO_MOUNT && npm install"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: 1026

#  Leaving this here for now, as an example of how to use other docker images
#  compass:
#    type: compose
#    services:
#      image: antonienko/compass-watch
#      command: watch --poll /src/compass
#    description: run compass- use lando compass

tooling:
  drush:
    service: appserver
    description: run drush commands
    cmd: /app/vendor/drush/drush/drush
  phpunit:
    service: appserver
    description: run PHPUnit- use lando phpunit
  behat:
    service: appserver
    description: run behat- use lando behat
    cmd: cd /app ; behat  # Run behat from the /app  directory
  mailhog:
    service: mailhog
  node:
    service: node
  npm:
    service: node
  gulp:
    service: node
